-- MySQL Script generated by MySQL Workbench
-- Thu May  6 00:06:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- TAbela `Zamówienia`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Zamówienia` (
  `idZamówienia` INT NOT NULL,
  `idUser` INT NOT NULL,
  `idZapłaty` INT NOT NULL,
  `DataWypożyczenia` DATE NOT NULL,
  `DataOddania` DATE NOT NULL,
  `idSamochody` INT NOT NULL
)
ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

INSERT INTO `Zamówienia` (`idZamówienia`, `idUser`, `idZapłaty`, `DataWypożyczenia`, `DataOddania`, `idSamochody`) VALUES
(1, 1, 1, '2021-05-06', '2021-05-07', 3),
(2, 4, 2, '2021-05-06', '2021-05-09', 1),
(3, 2, 3, '2021-05-07', '2021-06-03', 4),
(4, 1, 4, '2021-05-10', '2021-05-20', 1),
(5, 3, 5, '2021-05-06', '2021-05-07', 2);


-- -----------------------------------------------------
-- TAbela `User`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `User` (
  `idUser` INT NOT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Nazwisko` VARCHAR(45) NOT NULL,
  `Imię` VARCHAR(45) NOT NULL,
  `Pesel` INT(11) NOT NULL,
  `Miasto` VARCHAR(45) NOT NULL,
  `Ulica` VARCHAR(45) NOT NULL,
  `Kod_pocztowy` VARCHAR(6) NOT NULL,
  `Telefon` INT(9) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Rodzaj` VARCHAR(45) NOT NULL
  )
ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

INSERT INTO `User` (`idUser`, `Login`, `Password`, `Nazwisko`, `Imię`, `Pesel`, `Miasto`, `Ulica`, `Kod_pocztowy`, `Telefon`, `Email`, `Rodzaj`) VALUES
(1, 'User1', 'User1', 'Nowak', 'Jan', 90092800006, 'Wrocław', 'Długa 18', '50-139', 503853690, 'janek@gmail.com', 'klient'),
(2, 'Worker1', 'Worker1', 'Kowalski', 'Marek', 88022206074, 'Karwiany', 'Morelowa 1', '52-200', 790438883, 'mk@gmail.com', 'worker'),
(3, 'User2', 'User2', 'Ilak', 'Paulina', 20010809601, 'Wrocław', 'Oławska 87', '50-149', 607963777, 'motylek213@gmail.com', 'klient'),
(4, 'User3', 'User3', 'Rodek', 'Krzysztof', 70031290006, 'Wrocław', 'Krzywoustego 104/12', '52-050', 601855901, 'jatoja@gmail.com', 'klient'),
(5, 'User4', 'User4', 'Iksiński', 'Mirosław', 90022890062, 'Opole', 'Prosta 1', '38-109', 888369075, 'atak78a@gmail.com', 'klient');


-- -----------------------------------------------------
-- Tabela `Samochody`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `Samochody` (
  `idSamochody` INT NOT NULL,
  `Marka` VARCHAR(45) NOT NULL,
  `Model` VARCHAR(45) NOT NULL,
  `Nr_rejestracyjny` VARCHAR(7) NOT NULL,
  `Rok_produkcji` INT(4) NOT NULL,
  `Pojemność_(l)` DECIMAL NOT NULL,
  `Rodzaj_paliwa` VARCHAR(45) NOT NULL,
  `Moc_(km)` INT NOT NULL,
  `idUser` INT NOT NULL
  )
ENGINE = InnoDB DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

INSERT INTO `Samochody` (`idSamochody`, `Marka`, `Model`, `Nr_rejestracyjny`, `Rok_produkcji`, `Pojemność_(l)`, `Rodzaj_paliwa`, `Moc_(km)`, `idUser`) VALUES
(1, 'Toyota', 'Auris', 'DW99001', 2018, '1,5' , 'Diesel', 90, 2),
(2, 'Toyota', 'Corolla', 'DW99002', 2019, '1,5' , 'Diesel', 115, 5),
(3, 'Ford', 'Focus', 'DW99103', 2020, '1,0' , 'Benzyna', 150, 1),
(4, 'Hyundai', 'Tuscon', 'DW99004', 2020, '2,0' , 'Hybryda', 170, 3),
(5, 'Skoda', 'Octavia', 'DW99960', 2019, '1,9' , 'Benzyna', 190, 4);



-- -----------------------------------------------------
-- Indeksy dla tabeli `Zamówienia`
-- -----------------------------------------------------
ALTER TABLE `Zamówienia`
  ADD PRIMARY KEY (`idZamówienia`),
  ADD KEY `idUser` (`idUser`),
  ADD KEY `idSamochody` (`idSamochody`);


-- -----------------------------------------------------
-- Indeksy dla tabeli `User`
-- -----------------------------------------------------
ALTER TABLE `User`
  ADD PRIMARY KEY (`idUser`);


-- -----------------------------------------------------
-- Indeksy dla tabeli `Samochody`
-- -----------------------------------------------------
ALTER TABLE `Samochody`
  ADD PRIMARY KEY (`idSamochody`),
  ADD KEY `idUser` (`idUser`);
  
  
  
  
-- -----------------------------------------------------
-- AUTO_INCREMENT dla tabeli 'Zamówienia'
-- -----------------------------------------------------
ALTER TABLE `Zamówienia`
  MODIFY `idZamówienia` int NOT NULL AUTO_INCREMENT;


-- -----------------------------------------------------
-- AUTO_INCREMENT dla tabeli 'User'
-- -----------------------------------------------------
ALTER TABLE `User`
  MODIFY `idUser` int NOT NULL AUTO_INCREMENT;


-- -----------------------------------------------------
-- AUTO_INCREMENT dla tabeli 'Samochody'
-- -----------------------------------------------------
ALTER TABLE `Samochody`
  MODIFY `idSamochody` int NOT NULL AUTO_INCREMENT;




-- -----------------------------------------------------
-- CONSTRAINNT dla tabeli 'Zamówienia'
-- -----------------------------------------------------
ALTER TABLE `Zamówienia`
  ADD CONSTRAINT `Zamówienia_1` 
	FOREIGN KEY (`idUser`) 
		REFERENCES `User` (`idUser`),
        
  ADD CONSTRAINT `Zamówienia_2` 
	FOREIGN KEY (`idSamochody`) 
		REFERENCES `Samochody` (`idSamochody`);

-- -----------------------------------------------------
-- CONSTRAINNT dla tabeli 'Samochody'
-- -----------------------------------------------------
ALTER TABLE `Samochody`
  ADD CONSTRAINT `Samochod_1` 
	FOREIGN KEY (`idUser`) 
		REFERENCES `User` (`idUser`);

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
